[book]
authors = ["Henk Oordt", "Marc Schoolderman", "Folkert de Vries", "Ruben Nijveld"]
title = "Rust 101 - Exercises"

src = "book"
language = "en"
multilingual = false

[build]
build-dir = "./target/book"
